#########################################################
# 2014 Marco Mastrodonato(c)
# This is a Rails 4.0 template to use with activeleonardo gem
# https://rubygems.org/gems/active_leonardo
# https://github.com/marcomd/Active_Leonardo
# 
# USAGE: rails new yourappname -m active_template.rb
# 
# -------------------------------------------------------
#
#########################################################
ANSWERS = ARGV[3]
puts '*' * 80
say("* Processing template...", :red)
puts '*' * 80

test_mode = nil
ARGV.each{|arg| test_mode = true if arg  == "test_mode"}
app_path = ARGV[0]
say_status("**** Starting app into #{app_path} in test mode! ****\n")  if test_mode
#puts "**** Starting app into #{app_path} in test mode! ****" if test_mode

if ANSWERS && !test_mode
  puts '*'*80, '';
  puts "Answers:       #{ANSWERS}"
  puts "use_git        #{ANSWERS[0]}"
  puts "easy_develop   #{ANSWERS[1]}"
  puts "rspec          #{ANSWERS[2]}"
  puts "authentication #{ANSWERS[3]}"
  puts "authorization  #{ANSWERS[4]}"
  puts "handle_states  #{ANSWERS[5]}"
  puts "dashboard_root #{ANSWERS[6]}"
  puts "home           #{ANSWERS[7]}"
  puts "bundle_install #{ANSWERS[8]}"
  puts '*'*80, ''; sleep 0.25
end

## -------- QUESTIONS ---------
if ANSWERS
  use_git        = ANSWERS[0]
  easy_develop   = ANSWERS[1]
  rspec          = ANSWERS[2]
  authentication = ANSWERS[3]
  authorization  = ANSWERS[4]
  handle_states  = ANSWERS[5]
  dashboard_root = ANSWERS[6]
  home           = ANSWERS[7]
  bundle_install = ANSWERS[8]
else
  use_git        = test_mode || yes?("Do you use git ?", :blue)
  easy_develop   = test_mode || yes?("Do you want to make development easier?", :blue)
  rspec          = test_mode || yes?("Add rspec as testing framework ?", :blue)
  authentication = test_mode || yes?("Authentication ?", :blue)
  authorization  = test_mode || yes?("Authorization ?", :blue)
  handle_states  = test_mode || yes?("Do you have to handle states ?", :blue)
  dashboard_root = test_mode || yes?("Would you use dashboard as root ? (recommended)", :blue)
  home           = test_mode || yes?("Ok. Would you create home controller as root ?", :blue) unless dashboard_root
  bundle_install = test_mode || yes?("Bundle install ?", :blue)
end

puts '*' * 80
say("* Configuring git...", :red)
if use_git
  git :init
  remove_file ".gitignore"
  file ".gitignore", <<-EOS.gsub(/^    /, '')
    # See http://help.github.com/ignore-files/ for more about ignoring files.
    #
    # If you find yourself ignoring temporary files generated by your text editor
    # or operating system, you probably want to add a global ignore instead:
    #   git config --global core.excludesfile ~/.gitignore_global

    # Ignore bundler config
    /.bundle
    # Ignore the default SQLite database.
    /db/*.sqlite3
    # Ignore all logfiles and tempfiles.
    /log/*.log
    /tmp
    /nbproject
    /.idea
    lib/tasks/files/*
    /*.cmd
    /*.dat
    /config/initializers/secret_token.rb
  EOS
end
puts '*' * 80; sleep 0.5

puts '*' * 80
say("* Adding gems...", :red)
gem "activeadmin",    git: 'http://github.com/gregbell/active_admin.git'
if test_mode
  gem "active_leonardo", :path => "../../."
else
  gem "active_leonardo"
end
gem "jquery-turbolinks"
gem "bourbon"

if easy_develop
  gem "rack-mini-profiler", :group => :development
  gem "better_errors",      :group => :development
  gem "binding_of_caller",  :group => :development
  gem "quiet_assets",       :group => :development
  gem "awesome_print",      :group => :development
end

if rspec
  gem 'rspec-rails',                    :group => [:test, :development]
  gem 'capybara',                       :group => :test
  gem 'launchy',                        :group => :test
  gem 'database_cleaner',               :group => :test
  if /1.8.*/ === RUBY_VERSION
    gem 'factory_girl', '2.6.4',        :group => :test
    gem 'factory_girl_rails', '1.7.0',  :group => :test
  else
    gem 'factory_girl_rails',           :group => :test
  end
end

gem "cancan"        if authorization
gem 'state_machine' if handle_states
puts '*' * 80; sleep 0.5


puts '*' * 80
say("* Bundle install...", :red)
if bundle_install
  if ANSWERS
    dir = ""
  else
    dir = test_mode ? "" : ask(" Insert folder name to install locally: [blank=default gems path]")
  end
  run "bundle install #{"--path=#{dir}" unless dir.empty? || dir=='y'}"
end
puts '*' * 80; sleep 0.5

puts '*' * 80
say("* Starting generators...", :red)
model_name = authorization = nil
if authentication
  default_model_name = "User"
  if ANSWERS
    model_name = ""
  else
    model_name = test_mode ? "" : ask(" Insert model name: [#{default_model_name}]")
  end
  if model_name.empty? || model_name == 'y'
    model_name = default_model_name
  else
    model_name = model_name.classify
    stdout = <<-REMEM.gsub(/^    /, '')
    *************************************************************************
    Remember to add your auth class when you use active leonardo's generator.
    For example: 
    rails g leosca Product name price:decimal --auth_class=#{model_name}
    *************************************************************************
    REMEM
    p stdout
  end
end

generate "rspec:install" if rspec

generate "active_admin:install #{authentication ? model_name : "--skip-users"}"

if authorization
  generate "cancan:ability"
  generate "migration", "AddRolesMaskTo#{model_name}", "roles_mask:integer"
end
puts '*' * 80; sleep 0.5

puts '*' * 80
say("* Starting leolay...", :red)
generate  "leolay",
          "active", #specify theme
          "--auth_class=#{model_name}",
          (rspec ? nil : "--skip-rspec"),
          (authorization ? nil : "--skip-authorization"),
          (authentication ? nil : "--skip-authentication"),
          (test_mode || ANSWERS ? "--no-verbose" : nil)
puts '*' * 80; sleep 0.5

puts '*' * 80
say("* Last settings, migration and seeding...", :red)
if dashboard_root
  route "root :to => 'admin/dashboard#index'"
elsif home
  generate "controller", "home", "index"
  route "root :to => 'home#index'"
end
rake "db:create:all"
rake "db:migrate"
rake "db:seed"
puts '*' * 80; sleep 0.5

puts '*' * 80
say("* Committing...", :red)
if use_git
  git :add => "."
  git :commit => %Q{ -m "Initial commit" }
end
puts '*' * 80; sleep 0.5
puts "ENJOY!"