#########################################################
# 2014 Marco Mastrodonato(c)
# This is a Rails 4.0 template to use with activeleonardo gem
# https://rubygems.org/gems/active_leonardo
# https://github.com/marcomd/Active_Leonardo
# 
# USAGE: rails new yourappname -m active_template.rb
# 
# -------------------------------------------------------
#
#########################################################

puts '*' * 40
puts "* Processing template..."
puts '*' * 40

test_mode = nil
puts '-'*80, '';
puts "Answers: #{ARGV[3]}"
puts "use_git        #{ARGV[3][0]}"
puts "easy_develop   #{ARGV[3][1]}"
puts "rspec          #{ARGV[3][2]}"
puts "authentication #{ARGV[3][3]}"
puts "authorization  #{ARGV[3][4]}"
puts "handle_states  #{ARGV[3][5]}"
puts "dashboard_root #{ARGV[3][6]}"
puts "home           #{ARGV[3][7]}"
puts "bundle_install #{ARGV[3][8]}"
puts '-'*80, ''; sleep 0.25
ARGV.each{|arg| test_mode = true if arg  == "test_mode"}
app_path = ARGV[0]
puts "**** Starting app into #{app_path} in test mode! ****" if test_mode

## -------- QUESTIONS ---------
if ARGV[3]
  use_git        = ARGV[3][0]
  easy_develop   = ARGV[3][1]
  rspec          = ARGV[3][2]
  authentication = ARGV[3][3]
  authorization  = ARGV[3][4]
  handle_states  = ARGV[3][5]
  dashboard_root = ARGV[3][6]
  home           = ARGV[3][7]
  bundle_install = ARGV[3][8]
else
  use_git        = test_mode || yes?("Do you use git ?")
  easy_develop   = test_mode || yes?("Do you want to make development easier?")
  rspec          = test_mode || yes?("Add rspec as testing framework ?")
  authentication = test_mode || yes?("Authentication ?")
  authorization  = test_mode || yes?("Authorization ?")
  handle_states  = test_mode || yes?("Do you have to handle states ?")
  dashboard_root = test_mode || yes?("Would you use dashboard as root ? (recommended)")
  home           = test_mode || yes?("Ok. Would you create home controller as root ?") unless dashboard_root
  bundle_install = test_mode || yes?("Bundle install ?")
end

if use_git
  git :init
  remove_file ".gitignore"
  file ".gitignore", <<-EOS.gsub(/^    /, '')
    # See http://help.github.com/ignore-files/ for more about ignoring files.
    #
    # If you find yourself ignoring temporary files generated by your text editor
    # or operating system, you probably want to add a global ignore instead:
    #   git config --global core.excludesfile ~/.gitignore_global

    # Ignore bundler config
    /.bundle
    # Ignore the default SQLite database.
    /db/*.sqlite3
    # Ignore all logfiles and tempfiles.
    /log/*.log
    /tmp
    /nbproject
    /.idea
    lib/tasks/files/*
    /*.cmd
    /*.dat
    /config/initializers/secret_token.rb
  EOS
end

gem "activeadmin",    git: 'http://github.com/gregbell/active_admin.git'
if test_mode
  gem "active_leonardo", :path => "../../."
else
  gem "active_leonardo"
end
gem "jquery-turbolinks"
gem "bourbon"

if easy_develop
  gem "rack-mini-profiler", :group => :development
  gem "better_errors",      :group => :development
  gem "binding_of_caller",  :group => :development
  gem "awesome_print",      :group => :development
end

#use_editor = yes?("Do you want a wysihtml editor?")
#if use_editor
#  gem 'activeadmin-dragonfly', git: 'https://github.com/stefanoverna/activeadmin-dragonfly'
#  gem 'activeadmin-wysihtml5', git: 'https://github.com/stefanoverna/activeadmin-wysihtml5'
#end

if rspec
  gem 'rspec-rails',                    :group => [:test, :development]
  gem 'capybara',                       :group => :test
  gem 'launchy',                        :group => :test
  gem 'database_cleaner',               :group => :test
  if /1.8.*/ === RUBY_VERSION
    gem 'factory_girl', '2.6.4',        :group => :test
    gem 'factory_girl_rails', '1.7.0',  :group => :test
  else
    gem 'factory_girl_rails',           :group => :test
  end
end
gem "cancan"        if authorization
gem 'state_machine' if handle_states

if bundle_install
  if ARGV[3]
    dir = ""
  else
    dir = test_mode ? "" : ask(" Insert folder name to install locally: [blank=default gems path]")
  end
  run "bundle install #{"--path=#{dir}" unless dir.empty? || dir=='y'}"
end

model_name = authorization = nil
if authentication
  default_model_name = "User"
  if ARGV[3]
    model_name = ""
  else
    model_name = test_mode ? "" : ask(" Insert model name: [#{default_model_name}]")
  end
  if model_name.empty? || model_name == 'y'
    model_name = default_model_name
  else
    model_name = model_name.classify
    stdout = <<-REMEM.gsub(/^    /, '')
    *************************************************************************
    Remember to add your auth class when you use active leonardo's generator.
    For example: 
    rails g leosca Product name price:decimal --auth_class=#{model_name}
    *************************************************************************
    REMEM
    p stdout
  end
end

generate "rspec:install" if rspec

generate "active_admin:install #{authentication ? model_name : "--skip-users"}"

if authorization
  generate "cancan:ability"
  generate "migration", "AddRolesMaskTo#{model_name}", "roles_mask:integer"
end

generate  "leolay",
          "active", #specify theme
          "--auth_class=#{model_name}",
          (rspec ? nil : "--skip-rspec"),
          (authorization ? nil : "--skip-authorization"),
          (authentication ? nil : "--skip-authentication"),
          (test_mode ? "--no-verbose" : nil)


if dashboard_root
  route "root :to => 'admin/dashboard#index'"
elsif home
  generate "controller", "home", "index"
  route "root :to => 'home#index'"
end

rake "db:create:all"
rake "db:migrate"
rake "db:seed"

if use_git
  git :add => "."
  git :commit => %Q{ -m "Initial commit" }
end

puts "ENJOY!"